### ISSUE TITLE
preprocessing list

### ISSUE THREAD

**Issue by gykim-intellius** [intelliusAi/open-domain-chatbot#10]
## `preprocessing`이 필요한 문장

1. 코드가 포함된 문장
    -  flights = pd.read_csv('./flights.csv') flights.head() 이케하래요
2. 이모티콘으로 이루어진 문장
    - ^U^ ('ω') (^▽^) ∩'ω'∩
3. 사진, 이모티콘등의 토큰이 포함된 문장
    - #@시스템#기타# 이런 이벤트가 있네 ㅋ
4. 특수문자가 포함된 문장
    - [단독] "1천만 가구에 100만 원 상품권 · 체크카드 지급" <앵커> 오늘(27일) 8시 뉴스는...
5. 특정 문자가 많이 반복되는 문장 -> 반복되는 문자를 일정 개수로 줄여줘야함
    - 내가 주문할줄이야 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~광광우럭
6. url 이 포함된 문장
    - 'www.naver.com'여기서 보면 될걸
7. 문장의 글자가 70% 미만인 문장
8. 사용자 발화와 봇 응답의  `3-gram` or `2-gram`의 겹치는 정도가 80%이상인 문장
9. token의 길이가 2이하 128이상인 문장
    - 길이는 변경 가능. tokenizer를 선택한 후에 가능.

**Comment by gykim-intellius** [comment]
soynlp normalization
```
from soynlp.normalizer import *

emoticon_normalize('ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ쿠ㅜㅜㅜㅜㅜㅜ', num_repeats=3)
# 'ㅋㅋㅋㅜㅜㅜ'

repeat_normalize('와하하하하하하하하하핫', num_repeats=2)
# '와하하핫'
```

**Comment by intellius-sbkim** [comment]
soynlp repeat_normalize 정규식 수정  

```
repeat_normalize('10000원 완전 호다닥 보내주는데 좀 신기하기도하고 고맙기도하고 그랬어 zzzzzㅋㅋㅋㅋㅋ', num_repeats=2)
# '100원 완전 호다닥 보내주는데 좀.... 신기하기도하고 고맙기도하고 그랬어 zzㅋㅋ'
```

--> n개 이상 연속 문자 탐지에서 숫자 제외 & 특수문자 추가  
 
```
import re

repeatchars_pattern = re.compile('(\D)\\1{2,}')
doublespace_pattern = re.compile('\s+')

def repeat_normalize(sent, num_repeats=2):
    if num_repeats > 0:
        sent = repeatchars_pattern.sub('\\1' * num_repeats, sent)
    sent = doublespace_pattern.sub(' ', sent)
    return sent.strip()
```

```
repeat_normalize('10000원 완전 호다닥 보내주는데 좀 신기하기도하고 고맙기도하고 그랬어 zzzzzㅋㅋㅋㅋㅋ', num_repeats=2)
# '10000원 완전 호다닥 보내주는데 좀.. 신기하기도하고 고맙기도하고 그랬어 zzㅋㅋ'
```

**Comment by gykim-intellius** [comment]
#11 로 이동하여 이 이슈는 `close`하겠습니다.
